# MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/taskmanager

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
# Security
# Tắt proactive auth để AuthFilter tự xử lý token thay vì Quarkus interceptrước
quarkus.http.auth.proactive=false

# JWT (SmallRye)
mp.jwt.verify.issuer=taskmanager-app
mp.jwt.verify.secret.key=my-super-secret-key-change-in-production-32ch
smallrye.jwt.verify.key.format=SECRET
smallrye.jwt.sign.key.format=SECRET
smallrye.jwt.verify.algorithm=HS256
app.jwt.expiry-hours=24